// generated by ModelGongGraphFileTemplate
package models

func IsStaged[Type Gongstruct](stage *StageStruct, instance *Type) (ok bool) {

	switch target := any(instance).(type) {
	// insertion point for stage
	case *EditorOutlet:
		ok = stage.IsStagedEditorOutlet(target)

	case *Outlet:
		ok = stage.IsStagedOutlet(target)

	case *TableOutlet:
		ok = stage.IsStagedTableOutlet(target)

	default:
		_ = target
	}
	return
}

// insertion point for stage per struct
	func (stage *StageStruct) IsStagedEditorOutlet(editoroutlet *EditorOutlet) (ok bool) {

		_, ok = stage.EditorOutlets[editoroutlet]
	
		return
	}

	func (stage *StageStruct) IsStagedOutlet(outlet *Outlet) (ok bool) {

		_, ok = stage.Outlets[outlet]
	
		return
	}

	func (stage *StageStruct) IsStagedTableOutlet(tableoutlet *TableOutlet) (ok bool) {

		_, ok = stage.TableOutlets[tableoutlet]
	
		return
	}


// StageBranch stages instance and apply StageBranch on all gongstruct instances that are
// referenced by pointers or slices of pointers of the insance
//
// the algorithm stops along the course of graph if a vertex is already staged
func StageBranch[Type Gongstruct](stage *StageStruct, instance *Type) {

	switch target := any(instance).(type) {
	// insertion point for stage branch
	case *EditorOutlet:
		stage.StageBranchEditorOutlet(target)

	case *Outlet:
		stage.StageBranchOutlet(target)

	case *TableOutlet:
		stage.StageBranchTableOutlet(target)

	default:
		_ = target
	}
}

// insertion point for stage branch per struct
func (stage *StageStruct) StageBranchEditorOutlet(editoroutlet *EditorOutlet) {

	// check if instance is already staged
	if IsStaged(stage, editoroutlet) {
		return
	}

	editoroutlet.Stage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}

func (stage *StageStruct) StageBranchOutlet(outlet *Outlet) {

	// check if instance is already staged
	if IsStaged(stage, outlet) {
		return
	}

	outlet.Stage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}

func (stage *StageStruct) StageBranchTableOutlet(tableoutlet *TableOutlet) {

	// check if instance is already staged
	if IsStaged(stage, tableoutlet) {
		return
	}

	tableoutlet.Stage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}


// UnstageBranch stages instance and apply UnstageBranch on all gongstruct instances that are
// referenced by pointers or slices of pointers of the insance
//
// the algorithm stops along the course of graph if a vertex is already staged
func UnstageBranch[Type Gongstruct](stage *StageStruct, instance *Type) {

	switch target := any(instance).(type) {
	// insertion point for unstage branch
	case *EditorOutlet:
		stage.UnstageBranchEditorOutlet(target)

	case *Outlet:
		stage.UnstageBranchOutlet(target)

	case *TableOutlet:
		stage.UnstageBranchTableOutlet(target)

	default:
		_ = target
	}
}

// insertion point for unstage branch per struct
func (stage *StageStruct) UnstageBranchEditorOutlet(editoroutlet *EditorOutlet) {

	// check if instance is already staged
	if ! IsStaged(stage, editoroutlet) {
		return
	}

	editoroutlet.Unstage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}

func (stage *StageStruct) UnstageBranchOutlet(outlet *Outlet) {

	// check if instance is already staged
	if ! IsStaged(stage, outlet) {
		return
	}

	outlet.Unstage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}

func (stage *StageStruct) UnstageBranchTableOutlet(tableoutlet *TableOutlet) {

	// check if instance is already staged
	if ! IsStaged(stage, tableoutlet) {
		return
	}

	tableoutlet.Unstage(stage)

	//insertion point for the staging of instances referenced by pointers

	//insertion point for the staging of instances referenced by slice of pointers

}

