// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { EditorOutletDB } from '../editoroutlet-db'
import { EditorOutletService } from '../editoroutlet.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-editoroutletstable',
  templateUrl: './editoroutlets-table.component.html',
  styleUrls: ['./editoroutlets-table.component.css'],
})
export class EditorOutletsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of EditorOutlet instances
  selection: SelectionModel<EditorOutletDB> = new (SelectionModel)
  initialSelection = new Array<EditorOutletDB>()

  // the data source for the table
  editoroutlets: EditorOutletDB[] = []
  matTableDataSource: MatTableDataSource<EditorOutletDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.editoroutlets
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (editoroutletDB: EditorOutletDB, property: string) => {
      switch (property) {
        case 'ID':
          return editoroutletDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return editoroutletDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (editoroutletDB: EditorOutletDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the editoroutletDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += editoroutletDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private editoroutletService: EditorOutletService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of editoroutlet instances
    public dialogRef: MatDialogRef<EditorOutletsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.editoroutletService.EditorOutletServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getEditorOutlets()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<EditorOutletDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getEditorOutlets()

    this.matTableDataSource = new MatTableDataSource(this.editoroutlets)
  }

  getEditorOutlets(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.editoroutlets = this.frontRepo.EditorOutlets_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let editoroutlet of this.editoroutlets) {
            let ID = this.dialogData.ID
            let revPointer = editoroutlet[this.dialogData.ReversePointer as keyof EditorOutletDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(editoroutlet)
            }
            this.selection = new SelectionModel<EditorOutletDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, EditorOutletDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to EditorOutletDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as EditorOutletDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let editoroutlet = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as EditorOutletDB
              this.initialSelection.push(editoroutlet)
            }
          }

          this.selection = new SelectionModel<EditorOutletDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.editoroutlets
      }
    )
  }

  // newEditorOutlet initiate a new editoroutlet
  // create a new EditorOutlet objet
  newEditorOutlet() {
  }

  deleteEditorOutlet(editoroutletID: number, editoroutlet: EditorOutletDB) {
    // list of editoroutlets is truncated of editoroutlet before the delete
    this.editoroutlets = this.editoroutlets.filter(h => h !== editoroutlet);

    this.editoroutletService.deleteEditorOutlet(editoroutletID, this.GONG__StackPath).subscribe(
      editoroutlet => {
        this.editoroutletService.EditorOutletServiceChanged.next("delete")
      }
    );
  }

  editEditorOutlet(editoroutletID: number, editoroutlet: EditorOutletDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(editoroutletID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "editoroutlet" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, editoroutletID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.editoroutlets.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.editoroutlets.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<EditorOutletDB>()

      // reset all initial selection of editoroutlet that belong to editoroutlet
      for (let editoroutlet of this.initialSelection) {
        let index = editoroutlet[this.dialogData.ReversePointer as keyof EditorOutletDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(editoroutlet)

      }

      // from selection, set editoroutlet that belong to editoroutlet
      for (let editoroutlet of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = editoroutlet[this.dialogData.ReversePointer as keyof EditorOutletDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(editoroutlet)
      }


      // update all editoroutlet (only update selection & initial selection)
      for (let editoroutlet of toUpdate) {
        this.editoroutletService.updateEditorOutlet(editoroutlet, this.GONG__StackPath)
          .subscribe(editoroutlet => {
            this.editoroutletService.EditorOutletServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, EditorOutletDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedEditorOutlet = new Set<number>()
      for (let editoroutlet of this.initialSelection) {
        if (this.selection.selected.includes(editoroutlet)) {
          // console.log("editoroutlet " + editoroutlet.Name + " is still selected")
        } else {
          console.log("editoroutlet " + editoroutlet.Name + " has been unselected")
          unselectedEditorOutlet.add(editoroutlet.ID)
          console.log("is unselected " + unselectedEditorOutlet.has(editoroutlet.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let editoroutlet = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as EditorOutletDB
      if (unselectedEditorOutlet.has(editoroutlet.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<EditorOutletDB>) = new Array<EditorOutletDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          editoroutlet => {
            if (!this.initialSelection.includes(editoroutlet)) {
              // console.log("editoroutlet " + editoroutlet.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + editoroutlet.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = editoroutlet.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = editoroutlet.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("editoroutlet " + editoroutlet.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<EditorOutletDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
