// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { TriageDB } from '../triage-db'
import { TriageService } from '../triage.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-triagestable',
  templateUrl: './triages-table.component.html',
  styleUrls: ['./triages-table.component.css'],
})
export class TriagesTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Triage instances
  selection: SelectionModel<TriageDB> = new (SelectionModel)
  initialSelection = new Array<TriageDB>()

  // the data source for the table
  triages: TriageDB[] = []
  matTableDataSource: MatTableDataSource<TriageDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.triages
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (triageDB: TriageDB, property: string) => {
      switch (property) {
        case 'ID':
          return triageDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return triageDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (triageDB: TriageDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the triageDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += triageDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private triageService: TriageService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of triage instances
    public dialogRef: MatDialogRef<TriagesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.triageService.TriageServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getTriages()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<TriageDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getTriages()

    this.matTableDataSource = new MatTableDataSource(this.triages)
  }

  getTriages(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.triages = this.frontRepo.Triages_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let triage of this.triages) {
            let ID = this.dialogData.ID
            let revPointer = triage[this.dialogData.ReversePointer as keyof TriageDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(triage)
            }
            this.selection = new SelectionModel<TriageDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TriageDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to TriageDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as TriageDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let triage = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TriageDB
              this.initialSelection.push(triage)
            }
          }

          this.selection = new SelectionModel<TriageDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.triages
      }
    )
  }

  // newTriage initiate a new triage
  // create a new Triage objet
  newTriage() {
  }

  deleteTriage(triageID: number, triage: TriageDB) {
    // list of triages is truncated of triage before the delete
    this.triages = this.triages.filter(h => h !== triage);

    this.triageService.deleteTriage(triageID, this.GONG__StackPath).subscribe(
      triage => {
        this.triageService.TriageServiceChanged.next("delete")
      }
    );
  }

  editTriage(triageID: number, triage: TriageDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(triageID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "triage" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, triageID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.triages.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.triages.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<TriageDB>()

      // reset all initial selection of triage that belong to triage
      for (let triage of this.initialSelection) {
        let index = triage[this.dialogData.ReversePointer as keyof TriageDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(triage)

      }

      // from selection, set triage that belong to triage
      for (let triage of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = triage[this.dialogData.ReversePointer as keyof TriageDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(triage)
      }


      // update all triage (only update selection & initial selection)
      for (let triage of toUpdate) {
        this.triageService.updateTriage(triage, this.GONG__StackPath)
          .subscribe(triage => {
            this.triageService.TriageServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TriageDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedTriage = new Set<number>()
      for (let triage of this.initialSelection) {
        if (this.selection.selected.includes(triage)) {
          // console.log("triage " + triage.Name + " is still selected")
        } else {
          console.log("triage " + triage.Name + " has been unselected")
          unselectedTriage.add(triage.ID)
          console.log("is unselected " + unselectedTriage.has(triage.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let triage = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TriageDB
      if (unselectedTriage.has(triage.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<TriageDB>) = new Array<TriageDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          triage => {
            if (!this.initialSelection.includes(triage)) {
              // console.log("triage " + triage.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + triage.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = triage.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = triage.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("triage " + triage.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<TriageDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
