// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { TableOutletDB } from '../tableoutlet-db'
import { TableOutletService } from '../tableoutlet.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-tableoutletstable',
  templateUrl: './tableoutlets-table.component.html',
  styleUrls: ['./tableoutlets-table.component.css'],
})
export class TableOutletsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of TableOutlet instances
  selection: SelectionModel<TableOutletDB> = new (SelectionModel)
  initialSelection = new Array<TableOutletDB>()

  // the data source for the table
  tableoutlets: TableOutletDB[] = []
  matTableDataSource: MatTableDataSource<TableOutletDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.tableoutlets
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (tableoutletDB: TableOutletDB, property: string) => {
      switch (property) {
        case 'ID':
          return tableoutletDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return tableoutletDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (tableoutletDB: TableOutletDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the tableoutletDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += tableoutletDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private tableoutletService: TableOutletService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of tableoutlet instances
    public dialogRef: MatDialogRef<TableOutletsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.tableoutletService.TableOutletServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getTableOutlets()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<TableOutletDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getTableOutlets()

    this.matTableDataSource = new MatTableDataSource(this.tableoutlets)
  }

  getTableOutlets(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.tableoutlets = this.frontRepo.TableOutlets_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let tableoutlet of this.tableoutlets) {
            let ID = this.dialogData.ID
            let revPointer = tableoutlet[this.dialogData.ReversePointer as keyof TableOutletDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(tableoutlet)
            }
            this.selection = new SelectionModel<TableOutletDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TableOutletDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to TableOutletDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as TableOutletDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let tableoutlet = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TableOutletDB
              this.initialSelection.push(tableoutlet)
            }
          }

          this.selection = new SelectionModel<TableOutletDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.tableoutlets
      }
    )
  }

  // newTableOutlet initiate a new tableoutlet
  // create a new TableOutlet objet
  newTableOutlet() {
  }

  deleteTableOutlet(tableoutletID: number, tableoutlet: TableOutletDB) {
    // list of tableoutlets is truncated of tableoutlet before the delete
    this.tableoutlets = this.tableoutlets.filter(h => h !== tableoutlet);

    this.tableoutletService.deleteTableOutlet(tableoutletID, this.GONG__StackPath).subscribe(
      tableoutlet => {
        this.tableoutletService.TableOutletServiceChanged.next("delete")
      }
    );
  }

  editTableOutlet(tableoutletID: number, tableoutlet: TableOutletDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(tableoutletID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "tableoutlet" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, tableoutletID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.tableoutlets.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.tableoutlets.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<TableOutletDB>()

      // reset all initial selection of tableoutlet that belong to tableoutlet
      for (let tableoutlet of this.initialSelection) {
        let index = tableoutlet[this.dialogData.ReversePointer as keyof TableOutletDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(tableoutlet)

      }

      // from selection, set tableoutlet that belong to tableoutlet
      for (let tableoutlet of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = tableoutlet[this.dialogData.ReversePointer as keyof TableOutletDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(tableoutlet)
      }


      // update all tableoutlet (only update selection & initial selection)
      for (let tableoutlet of toUpdate) {
        this.tableoutletService.updateTableOutlet(tableoutlet, this.GONG__StackPath)
          .subscribe(tableoutlet => {
            this.tableoutletService.TableOutletServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, TableOutletDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedTableOutlet = new Set<number>()
      for (let tableoutlet of this.initialSelection) {
        if (this.selection.selected.includes(tableoutlet)) {
          // console.log("tableoutlet " + tableoutlet.Name + " is still selected")
        } else {
          console.log("tableoutlet " + tableoutlet.Name + " has been unselected")
          unselectedTableOutlet.add(tableoutlet.ID)
          console.log("is unselected " + unselectedTableOutlet.has(tableoutlet.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let tableoutlet = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as TableOutletDB
      if (unselectedTableOutlet.has(tableoutlet.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<TableOutletDB>) = new Array<TableOutletDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          tableoutlet => {
            if (!this.initialSelection.includes(tableoutlet)) {
              // console.log("tableoutlet " + tableoutlet.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + tableoutlet.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = tableoutlet.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = tableoutlet.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("tableoutlet " + tableoutlet.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<TableOutletDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
