// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { EditorOutletDB } from '../editoroutlet-db'
import { EditorOutletService } from '../editoroutlet.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-editoroutlet-sorting',
  templateUrl: './editoroutlet-sorting.component.html',
  styleUrls: ['./editoroutlet-sorting.component.css']
})
export class EditorOutletSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of EditorOutlet instances that are in the association
  associatedEditorOutlets = new Array<EditorOutletDB>();

  constructor(
    private editoroutletService: EditorOutletService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of editoroutlet instances
    public dialogRef: MatDialogRef<EditorOutletSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getEditorOutlets()
  }

  getEditorOutlets(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let editoroutlet of this.frontRepo.EditorOutlets_array) {
          let ID = this.dialogData.ID
          let revPointerID = editoroutlet[this.dialogData.ReversePointer as keyof EditorOutletDB] as unknown as NullInt64
          let revPointerID_Index = editoroutlet[this.dialogData.ReversePointer + "_Index" as keyof EditorOutletDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedEditorOutlets.push(editoroutlet)
          }
        }

        // sort associated editoroutlet according to order
        this.associatedEditorOutlets.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedEditorOutlets, event.previousIndex, event.currentIndex);

    // set the order of EditorOutlet instances
    let index = 0

    for (let editoroutlet of this.associatedEditorOutlets) {
      let revPointerID_Index = editoroutlet[this.dialogData.ReversePointer + "_Index" as keyof EditorOutletDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedEditorOutlets.forEach(
      editoroutlet => {
        this.editoroutletService.updateEditorOutlet(editoroutlet, this.dialogData.GONG__StackPath)
          .subscribe(editoroutlet => {
            this.editoroutletService.EditorOutletServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
