// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { EditorOutletDB } from './editoroutlet-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class EditorOutletService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  EditorOutletServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private editoroutletsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.editoroutletsUrl = origin + '/api/github.com/fullstack-lang/gongrouter/go/v1/editoroutlets';
  }

  /** GET editoroutlets from the server */
  getEditorOutlets(GONG__StackPath: string): Observable<EditorOutletDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<EditorOutletDB[]>(this.editoroutletsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched editoroutlets')),
        catchError(this.handleError<EditorOutletDB[]>('getEditorOutlets', []))
      );
  }

  /** GET editoroutlet by id. Will 404 if id not found */
  getEditorOutlet(id: number, GONG__StackPath: string): Observable<EditorOutletDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.editoroutletsUrl}/${id}`;
    return this.http.get<EditorOutletDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched editoroutlet id=${id}`)),
      catchError(this.handleError<EditorOutletDB>(`getEditorOutlet id=${id}`))
    );
  }

  /** POST: add a new editoroutlet to the server */
  postEditorOutlet(editoroutletdb: EditorOutletDB, GONG__StackPath: string): Observable<EditorOutletDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<EditorOutletDB>(this.editoroutletsUrl, editoroutletdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted editoroutletdb id=${editoroutletdb.ID}`)
      }),
      catchError(this.handleError<EditorOutletDB>('postEditorOutlet'))
    );
  }

  /** DELETE: delete the editoroutletdb from the server */
  deleteEditorOutlet(editoroutletdb: EditorOutletDB | number, GONG__StackPath: string): Observable<EditorOutletDB> {
    const id = typeof editoroutletdb === 'number' ? editoroutletdb : editoroutletdb.ID;
    const url = `${this.editoroutletsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<EditorOutletDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted editoroutletdb id=${id}`)),
      catchError(this.handleError<EditorOutletDB>('deleteEditorOutlet'))
    );
  }

  /** PUT: update the editoroutletdb on the server */
  updateEditorOutlet(editoroutletdb: EditorOutletDB, GONG__StackPath: string): Observable<EditorOutletDB> {
    const id = typeof editoroutletdb === 'number' ? editoroutletdb : editoroutletdb.ID;
    const url = `${this.editoroutletsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<EditorOutletDB>(url, editoroutletdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated editoroutletdb id=${editoroutletdb.ID}`)
      }),
      catchError(this.handleError<EditorOutletDB>('updateEditorOutlet'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in EditorOutletService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("EditorOutletService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
