// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TableOutletDB } from './tableoutlet-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class TableOutletService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TableOutletServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private tableoutletsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.tableoutletsUrl = origin + '/api/github.com/fullstack-lang/gongrouter/go/v1/tableoutlets';
  }

  /** GET tableoutlets from the server */
  getTableOutlets(GONG__StackPath: string): Observable<TableOutletDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<TableOutletDB[]>(this.tableoutletsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched tableoutlets')),
        catchError(this.handleError<TableOutletDB[]>('getTableOutlets', []))
      );
  }

  /** GET tableoutlet by id. Will 404 if id not found */
  getTableOutlet(id: number, GONG__StackPath: string): Observable<TableOutletDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.tableoutletsUrl}/${id}`;
    return this.http.get<TableOutletDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched tableoutlet id=${id}`)),
      catchError(this.handleError<TableOutletDB>(`getTableOutlet id=${id}`))
    );
  }

  /** POST: add a new tableoutlet to the server */
  postTableOutlet(tableoutletdb: TableOutletDB, GONG__StackPath: string): Observable<TableOutletDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TableOutletDB>(this.tableoutletsUrl, tableoutletdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted tableoutletdb id=${tableoutletdb.ID}`)
      }),
      catchError(this.handleError<TableOutletDB>('postTableOutlet'))
    );
  }

  /** DELETE: delete the tableoutletdb from the server */
  deleteTableOutlet(tableoutletdb: TableOutletDB | number, GONG__StackPath: string): Observable<TableOutletDB> {
    const id = typeof tableoutletdb === 'number' ? tableoutletdb : tableoutletdb.ID;
    const url = `${this.tableoutletsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<TableOutletDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted tableoutletdb id=${id}`)),
      catchError(this.handleError<TableOutletDB>('deleteTableOutlet'))
    );
  }

  /** PUT: update the tableoutletdb on the server */
  updateTableOutlet(tableoutletdb: TableOutletDB, GONG__StackPath: string): Observable<TableOutletDB> {
    const id = typeof tableoutletdb === 'number' ? tableoutletdb : tableoutletdb.ID;
    const url = `${this.tableoutletsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<TableOutletDB>(url, tableoutletdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated tableoutletdb id=${tableoutletdb.ID}`)
      }),
      catchError(this.handleError<TableOutletDB>('updateTableOutlet'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in TableOutletService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("TableOutletService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
