// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TriageDB } from './triage-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class TriageService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TriageServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private triagesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.triagesUrl = origin + '/api/github.com/fullstack-lang/gongrouter/go/v1/triages';
  }

  /** GET triages from the server */
  getTriages(GONG__StackPath: string): Observable<TriageDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<TriageDB[]>(this.triagesUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched triages')),
        catchError(this.handleError<TriageDB[]>('getTriages', []))
      );
  }

  /** GET triage by id. Will 404 if id not found */
  getTriage(id: number, GONG__StackPath: string): Observable<TriageDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.triagesUrl}/${id}`;
    return this.http.get<TriageDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched triage id=${id}`)),
      catchError(this.handleError<TriageDB>(`getTriage id=${id}`))
    );
  }

  /** POST: add a new triage to the server */
  postTriage(triagedb: TriageDB, GONG__StackPath: string): Observable<TriageDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<TriageDB>(this.triagesUrl, triagedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted triagedb id=${triagedb.ID}`)
      }),
      catchError(this.handleError<TriageDB>('postTriage'))
    );
  }

  /** DELETE: delete the triagedb from the server */
  deleteTriage(triagedb: TriageDB | number, GONG__StackPath: string): Observable<TriageDB> {
    const id = typeof triagedb === 'number' ? triagedb : triagedb.ID;
    const url = `${this.triagesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<TriageDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted triagedb id=${id}`)),
      catchError(this.handleError<TriageDB>('deleteTriage'))
    );
  }

  /** PUT: update the triagedb on the server */
  updateTriage(triagedb: TriageDB, GONG__StackPath: string): Observable<TriageDB> {
    const id = typeof triagedb === 'number' ? triagedb : triagedb.ID;
    const url = `${this.triagesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<TriageDB>(url, triagedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated triagedb id=${triagedb.ID}`)
      }),
      catchError(this.handleError<TriageDB>('updateTriage'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in TriageService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("TriageService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
